### ISSUE TITLE
Setting response status code doesn't seem to work

### ISSUE THREAD

**Issue by siematypie** [tiagodaraujo/HttpContextMoq#5]
Hey! First of all thanks for creating this library :) 

I want to test some code that sets the status code of the response:

`
                context.Response.StatusCode = StatusCodes.Status404NotFound;
`
Unfortunately, it seems that setting this inside mock does not work - it still have default value (0)
Can you take a look? :)

**Comment by tiagodaraujo** [comment]
Hi @siematypie

I think you could mock the `StatusCode` to get the `StatusCodes.Status404NotFound`.

`contextMock.ResponseMock.Mock.Setup(r => r.StatusCode).Returns(StatusCodes.Status404NotFound)`

otherwise, as an integer, the `StatusCode` will return a 0.

since you are setting a value, you can verify the value after that `contextMock.ResponseMock.Mock.VerifySet(r => r.StatusCode = StatusCodes.Status404NotFound)`.

Sorry for the delay and I hope that HttpContextMoq is being useful for your projects.

**Comment by siematypie** [comment]
Hey @tiagodaraujo, I already figured that, just forgot to close the issue, initially I thought the library is working a little bit differently :D Thanks for the response, yeah it's supper useful :)
